version: "3"
services:
    https-portal:
        image: steveltn/https-portal:1
        ports:
            - '80:80'
            - '443:443'
        restart: always
        environment:
            DOMAINS: 'development.kumata.online -> http://web'
            STAGE: 'production'
            # FORCE_RENEW: 'true'
        volumes:
            - ./ssl-certs:/var/lib/ssl-certs

    app:
        build:
            context: ./docker/php
            args:
                - TZ=${TZ}
        ports:
            - ${APP_PORT}:8000
        volumes:
            - ${PROJECT_PATH}:/work
            - ./logs:/var/log/php
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /work/SoftTennisSkillAnalyzer
        environment:
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USER}
            - DB_PASSWORD=${DB_PASS}
            - TZ=${TZ}
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_PORT=${MAIL_PORT}

    web:
        image: nginx:1.17-alpine
        depends_on:
            - app
        volumes:
            - ${PROJECT_PATH}:/work
            - ./logs:/var/log/nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - TZ=${TZ}

    db:
        image: mysql:8.0
        volumes:
        - db-store:/var/lib/mysql
        - ./logs:/var/log/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
            - TZ=${TZ}
        ports:
            - ${DB_PORT}:3306
      
volumes:
    db-store: